#!/bin/bash

cannon-rs generate dynamic-router --name OracleManagerRouter "@synthetixio/oracle-manager/contracts/modules/NodeModule.sol:NodeModule" "@synthetixio/oracle-manager/contracts/modules/CoreModule.sol:CoreModule"

cannon-rs generate dynamic-router  --name CoreRouter "@synthetixio/main/contracts/modules/InitialModuleBundle.sol:InitialModuleBundle" "@synthetixio/main/contracts/modules/core/FeatureFlagModule.sol:FeatureFlagModule" "@synthetixio/main/contracts/modules/core/AccountModule.sol:AccountModule" "@synthetixio/main/contracts/modules/core/AssociateDebtModule.sol:AssociateDebtModule" "@synthetixio/main/contracts/modules/associated-systems/AssociatedSystemsModule.sol:AssociatedSystemsModule" "@synthetixio/main/contracts/modules/core/CcipReceiverModule.sol:CcipReceiverModule" "@synthetixio/main/contracts/modules/core/CollateralModule.sol:CollateralModule" "@synthetixio/main/contracts/modules/core/CollateralConfigurationModule.sol:CollateralConfigurationModule" "@synthetixio/main/contracts/modules/core/CrossChainUSDModule.sol:CrossChainUSDModule" "@synthetixio/main/contracts/modules/core/IssueUSDModule.sol:IssueUSDModule" "@synthetixio/main/contracts/modules/core/LiquidationModule.sol:LiquidationModule" "@synthetixio/main/contracts/modules/core/MarketCollateralModule.sol:MarketCollateralModule" "@synthetixio/main/contracts/modules/core/MarketManagerModule.sol:MarketManagerModule" "@synthetixio/main/contracts/modules/core/PoolConfigurationModule.sol:PoolConfigurationModule" "@synthetixio/main/contracts/modules/core/PoolModule.sol:PoolModule" "@synthetixio/main/contracts/modules/core/RewardsManagerModule.sol:RewardsManagerModule" "@synthetixio/main/contracts/modules/core/UtilsModule.sol:UtilsModule" "@synthetixio/main/contracts/modules/core/VaultModule.sol:VaultModule"

cannon-rs generate dynamic-router   --name AccountRouter "@synthetixio/main/contracts/modules/InitialModuleBundle.sol:InitialModuleBundle" "@synthetixio/main/contracts/modules/account/AccountTokenModule.sol:AccountTokenModule"

cannon-rs generate dynamic-router  --name USDRouter "@synthetixio/main/contracts/modules/InitialModuleBundle.sol:InitialModuleBundle" "@synthetixio/main/contracts/modules/associated-systems/AssociatedSystemsModule.sol:AssociatedSystemsModule" "@synthetixio/main/contracts/modules/usd/USDTokenModule.sol:USDTokenModule"

cannon-rs generate dynamic-router  --name SpotMarketRouter  "@synthetixio/spot-market/contracts/modules/CoreModule.sol:CoreModule" "@synthetixio/spot-market/contracts/modules/SpotMarketFactoryModule.sol:SpotMarketFactoryModule" "@synthetixio/spot-market/contracts/modules/AtomicOrderModule.sol:AtomicOrderModule" "@synthetixio/spot-market/contracts/modules/AsyncOrderModule.sol:AsyncOrderModule" "@synthetixio/spot-market/contracts/modules/AsyncOrderSettlementModule.sol:AsyncOrderSettlementModule" "@synthetixio/spot-market/contracts/modules/AsyncOrderConfigurationModule.sol:AsyncOrderConfigurationModule" "@synthetixio/spot-market/contracts/modules/WrapperModule.sol:WrapperModule" "@synthetixio/spot-market/contracts/modules/MarketConfigurationModule.sol:MarketConfigurationModule" "@synthetixio/spot-market/contracts/modules/FeatureFlagModule.sol:FeatureFlagModule"

cannon-rs generate dynamic-router  --name SynthRouter "@synthetixio/spot-market/contracts/modules/CoreModule.sol:CoreModule" "@synthetixio/spot-market/contracts/modules/token/SynthTokenModule.sol:SynthTokenModule"

cannon-rs generate dynamic-router  --name PerpMarketRouter "@synthetixio/main/contracts/modules/core/AccountModule.sol:AccountModule" "@synthetixio/main/contracts/modules/associated-systems/AssociatedSystemsModule.sol:AssociatedSystemsModule" "@synthetixio/perps-market/contracts/modules/CoreModule.sol:CoreModule" "@synthetixio/perps-market/contracts/modules/PerpsMarketFactoryModule.sol:PerpsMarketFactoryModule" "@synthetixio/perps-market/contracts/modules/PerpsAccountModule.sol:PerpsAccountModule" "@synthetixio/perps-market/contracts/modules/PerpsMarketModule.sol:PerpsMarketModule" "@synthetixio/perps-market/contracts/modules/AsyncOrderModule.sol:AsyncOrderModule" "@synthetixio/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol:AsyncOrderSettlementPythModule" "@synthetixio/perps-market/contracts/modules/AsyncOrderCancelModule.sol:AsyncOrderCancelModule" "@synthetixio/perps-market/contracts/modules/FeatureFlagModule.sol:FeatureFlagModule" "@synthetixio/perps-market/contracts/modules/LiquidationModule.sol:LiquidationModule" "@synthetixio/perps-market/contracts/modules/MarketConfigurationModule.sol:MarketConfigurationModule" "@synthetixio/perps-market/contracts/modules/CollateralConfigurationModule.sol:CollateralConfigurationModule" "@synthetixio/perps-market/contracts/modules/GlobalPerpsMarketModule.sol:GlobalPerpsMarketModule"